# Generated by Django 6.1 on 2026-09-13 17:36

import django.db.models.deletion
import progress.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('progress', '0005_alter_courseprogress_options'),
        ('students', '0002_migrate_legacy_enrollments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=40)),
                ('cover_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('SHORTLISTED', 'Shortlisted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'permissions': [('review_opportunityapplication', 'Can review opportunity applications'), ('download_opportunityapplicationdocument', 'Can download application documents')],
            },
        ),
        migrations.CreateModel(
            name='OpportunityApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='application_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='application_mode',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='application_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='audience_groups',
            field=models.ManyToManyField(blank=True, related_name='career_opportunities', to='students.studentgroup'),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='audience_scope',
            field=models.CharField(choices=[('ALL_LEARNERS', 'All learners'), ('SELECTED_GROUPS', 'Selected groups')], db_index=True, default='ALL_LEARNERS', max_length=24),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='company_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_opportunities', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='company_website',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='compensation_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='compensation_disclosure',
            field=models.CharField(choices=[('NOT_DISCLOSED', 'Not disclosed'), ('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='NOT_DISCLOSED', max_length=20),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='compensation_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='compensation_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='compensation_pay_period',
            field=models.CharField(blank=True, choices=[('HOUR', 'Per hour'), ('DAY', 'Per day'), ('WEEK', 'Per week'), ('MONTH', 'Per month'), ('YEAR', 'Per year'), ('PROJECT', 'Per project')], max_length=20),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='cover_note_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='description_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='duration',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='eligibility_rules',
            field=models.JSONField(blank=True, default=progress.models.empty_eligibility_rules),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='employment_type',
            field=models.CharField(choices=[('INTERNSHIP', 'Internship'), ('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'Contract'), ('APPRENTICESHIP', 'Apprenticeship'), ('PROJECT', 'Project')], default='INTERNSHIP', max_length=24),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='legacy_kind',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='lifecycle_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='openings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='physical_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='remote_region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='resume_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careeropportunity',
            name='workplace_mode',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('IN_OFFICE', 'In office')], default='REMOTE', max_length=24),
        ),
        migrations.AddIndex(
            model_name='careeropportunity',
            index=models.Index(fields=['lifecycle_status', 'application_deadline'], name='opp_lifecycle_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='careeropportunity',
            index=models.Index(fields=['employment_type', 'workplace_mode'], name='opp_employment_work_idx'),
        ),
        migrations.AddIndex(
            model_name='careeropportunity',
            index=models.Index(fields=['is_featured', 'created_at'], name='opp_featured_created_idx'),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='progress.careeropportunity'),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_applications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunityapplicationdocument',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resume_document', to='progress.opportunityapplication'),
        ),
        migrations.AddIndex(
            model_name='opportunityapplication',
            index=models.Index(fields=['opportunity', 'status', 'submitted_at'], name='oppapp_opp_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityapplication',
            index=models.Index(fields=['applicant', 'status'], name='oppapp_applicant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunityapplication',
            constraint=models.UniqueConstraint(fields=('opportunity', 'applicant'), name='unique_opportunity_applicant'),
        ),
        migrations.AddConstraint(
            model_name='opportunityapplication',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN'])), name='valid_opportunity_application_status'),
        ),
    ]
