# Generated by Django 5.2 for the course-context chatbot change.
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("curriculum", "0003_extract_content_media"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseChatSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("context_revision", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("course_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="chat_sessions", to="curriculum.courseversion")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="course_chat_sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddIndex(
            model_name="coursechatsession",
            index=models.Index(fields=["student", "course_version", "is_active"], name="chat_sess_student_ver_idx"),
        ),
        migrations.CreateModel(
            name="CourseChatbotConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(db_index=True, default=False)),
                ("approved_context", models.TextField(blank=True)),
                ("context_revision", models.PositiveIntegerField(default=1)),
                ("course_version", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="chatbot_config", to="curriculum.courseversion")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="chatbot_configs_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["course_version__course__name", "-course_version__version_number"],
                "permissions": [("manage_course_chatbot", "Can manage course chatbot configuration")],
            },
        ),
        migrations.CreateModel(
            name="CourseChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("USER", "User"), ("ASSISTANT", "Assistant")], max_length=12)),
                ("content", models.TextField()),
                ("citations", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="tutoring.coursechatsession")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AddIndex(
            model_name="coursechatmessage",
            index=models.Index(fields=["session", "created_at"], name="chat_msg_session_created_idx"),
        ),
    ]
